# PYTHON REVIEW

This notebook reviews essential python data structures and control flows, including the numpy and pandas packages.
The notebook also reviews how to run and modify a Tellurium simulation.

$x_2 = \int f(g)$

In [2]:
a = 1

In [3]:

print(a)

1


In [4]:
a = 2

# The Colab Environment
* Setup
* Code and text cells
* Namespace persistence
* Formulas in text cells

# Elemental Types

In [5]:
1 + (1 == 2)

1

* str, float, int
* list (properties, slices), deep copy
* dict: reference, assign
* range function

In [6]:
alist = [1, 'str', True]
alist

[1, 'str', True]

In [7]:
alist[0]

1

In [8]:
a = ['time', 1, 2, 3, 4]
a[1], a[2], a[3], a[4]

(1, 2, 3, 4)

In [9]:
a[1:]

[1, 2, 3, 4]

In [10]:
a + a

['time', 1, 2, 3, 4, 'time', 1, 2, 3, 4]

In [11]:
import numpy as np

In [12]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [13]:
arr = np.array(a[1:])
arr

array([1, 2, 3, 4])

In [14]:
2*arr, np.exp(arr)

(array([2, 4, 6, 8]),
 array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003]))

In [15]:
# Dictionaries have a key (hashable) and value. They are good for associative lookup.
sentiment_dct ={
    'cat': 10,
    'dog': 2,
    'snakes': -1
}

# Are cats preferred to dogs?
sentiment_dct['cat'] > sentiment_dct['dog']

True

## Pandas DataFrames

### Creating

In [16]:
import pandas as pd

In [17]:
df = pd.DataFrame(arr)
df

0
0  1
1  2
2  3
3  4

In [18]:
dct = {'time': arr}
df = pd.DataFrame(dct)
df.index = ['w', 'x', 'y', 'z']
df

time
w     1
x     2
y     3
z     4

In [19]:
df['result'] = [10, 20, 30, 40]
df

time  result
w     1      10
x     2      20
y     3      30
z     4      40

In [20]:
# Arithmetic on rows
df['rate'] = df['result'] / df['time']
df

time  result  rate
w     1      10  10.0
x     2      20  10.0
y     3      30  10.0
z     4      40  10.0

In [21]:
# Add tables
df + df

time  result  rate
w     2      20  20.0
x     4      40  20.0
y     6      60  20.0
z     8      80  20.0

In [25]:
df2 = df.sort_values('result', ascending=False)
df2

time  result  rate
z     4      40  10.0
y     3      30  10.0
x     2      20  10.0
w     1      10  10.0

In [26]:
df + df2

time  result  rate
w     2      20  20.0
x     4      40  20.0
y     6      60  20.0
z     8      80  20.0

In [ ]:
# Add dataframes with unaligned rows

### Row & Column Names

In [28]:
# Column
df['result']

w    10
x    20
y    30
z    40
Name: result, dtype: int64

In [29]:
# Select a row
df.loc['w', :]

time       1.0
result    10.0
rate      10.0
Name: w, dtype: float64

### Converting to numpy arrays

### Arithmetic

### Reading and Writing CSV Files

### Merging & Pivoting

In [30]:
# Create a pivot table
dct = {'kP': [0, 1, 2, 3], 'kI': [0, 10, 20, 30], 'settling_time': [0.2, 2, 0.1, 40]}
exp_df = pd.DataFrame(dct)
exp_df

kP  kI  settling_time
0   0   0            0.2
1   1  10            2.0
2   2  20            0.1
3   3  30           40.0

In [31]:
pivot_df = exp_df.pivot_table(values='settling_time', index='kP', columns='kI')
pivot_df

kI   0    10   20    30
kP                     
0   0.2  NaN  NaN   NaN
1   NaN  2.0  NaN   NaN
2   NaN  NaN  0.1   NaN
3   NaN  NaN  NaN  40.0

### Plotting

# Python flow of control

* ``if``, ``elif``, ``else``
* ``for``
* ``def`` (functions) and requirements for writing functions

In [32]:
# for loop
alist = [1, 2, 3]
for i in arr:
    print(i)

1
2
3
4


In [35]:
# Conditionals
for i in arr:
    if i < 3:
        print('*', i)
    else:
        print('**', i)


* 1
* 2
** 3
** 4


In [46]:
# Functions
def foo(arg: int)->list:
    # Adds 1 to arg
    result = list(range(arg))
    return result

# Test
rslt = foo(3)
assert(rslt[0] == 0)
print("OK!")

OK!


In [43]:
rslt[1] == 0

False

# From Thought to Code

Write a function that returns true if the integer argument is prime.

In [69]:
value = 13
test_divisor = 2

not_prime = (value % test_divisor) == 0
not_prime

False

In [70]:
# Loop on all test_divisors
found_not_prime = False
for test_divisor in range(2, value):
    if value % test_divisor == 0:
        found_not_prime = True
# Is a prime
if found_not_prime:
    print("Not prime")
else:
    print("Prime")

Prime


In [71]:
def isPrime(value:int)->bool:
    # Check if value is prime
    found_not_prime = False
    for test_divisor in range(2, value):
        if value % test_divisor == 0:
            found_not_prime = True
    # Is a prime
    if found_not_prime:
        return False
    else:
        return True

# Tests
assert(isPrime(5))
assert(not isPrime(8))
print("OK!")

OK!


## From script to function

# Some programming problems

Write a function that takes as input an integer and outputs ``True`` if the number is prime and ``False`` otherwise.

Write a function that takes as input an integer and outputs all prime numbers less than or equal to that integer.

# Numpy linear algebra

* Create arrays
* Shaping arrays
* Indexing and slicing
* ``linspace``
* Array arithmetic
* Inverse of a matrix
* Eigenvalues, eigenvectors
* Singular value decomposition

# Plotting
* line and scatter plots
* changing the attributes of plots

# Tellurium and Antimony

* Simple model
* Load, simulate, plot
* Changes values of parameters
* Using simulation data directly
* Event statements
* Assignment statements