# PYTHON REVIEW

This notebook reviews essential python data structures and control flows, including the numpy and pandas packages.
The notebook also reviews how to run and modify a Tellurium simulation.

$x_2 = \int f(g)$

In [1]:
a = 1

In [2]:

print(a)

1


In [3]:
a = 2

# The Colab Environment
* Setup
* Code and text cells
* Namespace persistence
* Formulas in text cells

# Elemental Types

In [4]:
1 + (1 == 2)

1

* str, float, int
* list (properties, slices), deep copy
* dict: reference, assign
* range function

In [6]:
alist = [1, 'str', True]
alist

[1, 'str', True]

In [7]:
alist[0]

1

In [9]:
a = ['time', 1, 2, 3, 4]
a[1], a[2], a[3], a[4]

(1, 2, 3, 4)

In [10]:
a[1:]

[1, 2, 3, 4]

In [12]:
a + a

['time', 1, 2, 3, 4, 'time', 1, 2, 3, 4]

In [13]:
import numpy as np

In [14]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [15]:
arr = np.array(a[1:])
arr

array([1, 2, 3, 4])

In [17]:
2*arr, np.exp(arr)

(array([2, 4, 6, 8]),
 array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003]))

In [18]:
# Dictionaries have a key (hashable) and value. They are good for associative lookup.
sentiment_dct ={
    'cat': 10,
    'dog': 2,
    'snakes': -1
}

# Are cats preferred to dogs?
sentiment_dct['cat'] > sentiment_dct['dog']

True

## Pandas DataFrames

### Creating

In [19]:
import pandas as pd

In [21]:
df = pd.DataFrame(arr)
df

0
0  1
1  2
2  3
3  4

In [23]:
dct = {'time': arr}
df = pd.DataFrame(dct)
df.index = ['w', 'x', 'y', 'z']
df

time
w     1
x     2
y     3
z     4

### Row & Column Names

### Converting to numpy arrays

### Arithmetic

### Reading and Writing CSV Files

### Merging & Pivoting

### Plotting

# Python flow of control

* ``if``, ``elif``, ``else``
* ``for``
* ``def`` (functions) and requirements for writing functions

## From scrip to function

In [5]:
# A very bad way to test a script
a = -1
if a < 0:
    print("less than 0")
elif a == 0:
    print("a is 0")
else:
    print("a is greater than 0")

less than 0


# Some programming problems

Write a function that takes as input an integer and outputs ``True`` if the number is prime and ``False`` otherwise.

Write a function that takes as input an integer and outputs all prime numbers less than or equal to that integer.

# Numpy linear algebra

* Create arrays
* Shaping arrays
* Indexing and slicing
* ``linspace``
* Array arithmetic
* Inverse of a matrix
* Eigenvalues, eigenvectors
* Singular value decomposition

# Plotting
* line and scatter plots
* changing the attributes of plots

# Tellurium and Antimony

* Simple model
* Load, simulate, plot
* Changes values of parameters
* Using simulation data directly
* Event statements
* Assignment statements